/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bree_com_jnitest_JniMethods */

#ifndef _Included_bree_com_jnitest_JniMethods
#define _Included_bree_com_jnitest_JniMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bree_com_jnitest_JniMethods
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bree_com_jnitest_JniMethods_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
